name: tiresias
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - anaconda::make=4.2.1
  - python=3.7.2
  - matplotlib=3.0.3
  - anaconda::numpy=1.17.4
  - anaconda::scipy=1.3.2
  - pandas=0.25.3
  - scikit-learn=0.22
  - pytorch::pytorch=1.1.0
  - pytorch::torchvision=0.3.0
  - dglteam::dgl=0.2
  - pip=19.2.3
  - pip:
      - networkx==2.4
      - mlflow==1.5.0
      - ray==0.8.0
      - setproctitle==1.1.10
      - psutil==5.6.2
      - requests==2.21.0
      - rdflib==4.2.2
      - gensim==4.0.1
      - click==7.0
      - seaborn==0.9.0
      - pyyaml==5.2
      - "--editable=git+https://github.com/krishnanlab/PecanPy.git@0387c0ac8ac6607398781adbd6668aba17485b05#egg=pecanpy"
      - python-Levenshtein